ALTER TABLE usuarios  ADD COLUMN IF NOT EXISTS avatar_url  VARCHAR(500);
ALTER TABLE cursos    ADD COLUMN IF NOT EXISTS imagem_url  VARCHAR(500);
ALTER TABLE unidades  ADD COLUMN IF NOT EXISTS imagem_url  VARCHAR(500);
